name: CT AI Scan

# Controls when the workflow will run
on:
  push:
    branches: [ "master" ]
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [ "master" ]
jobs:
  codethreat_scanner:
    runs-on: ubuntu-latest
    name: Codethreat Github Actions
    steps:
      - name: Check Out Source Code
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v1
      - name: CodeThreat Scanner
        uses: CodeThreat/codethreat-scan-action@master
        env:
           ACCESS_TOKEN: ${{ secrets.CT_ACCESS_TOKEN }}
           GITHUB_TOKEN: ${{ secrets.CT_GITHUB_TOKEN }}
           CT_SERVER: ${{ secrets.CT_SERVER }}
           USERNAME: ${{ secrets.CT_USERNAME }}
           PASSWORD: ${{ secrets.CT_PASSWORD }}
           ORGNAME: ${{ secrets.CT_ORGNAME }}
        with: 
            FAILED_ARGS: |
                 - max_number_of_critical: 23
                 - max_number_of_high: 23
                 - weakness_is: ".*injection,buffer.over.read,mass.assigment"
                 - condition: 'OR'
                 - automerge: true
                 - sync_scan: true
                 - sca_max_number_of_critical: 23
                 - sca_max_number_of_high: 23
                 - policy_name: Advanced Security
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: codethreat.sarif.json
